export const MSG_TYPE_INIT = 'INIT';
export const MSG_TYPE_INIT_REPLY = 'INIT_REPLY';
export const MSG_TYPE_RPC_CALL = 'RPC_CALL';
export const MSG_TYPE_RPC_REPLY = 'RPC_CALL_REPLY';
export const MSG_TYPE_MESSAGE = 'MESSAGE';

export const INIT_SUCCESS = 'INIT_SUCCESS';
export const INIT_SUCCESS_PASSIVE = 'PASSIVE_INIT_SUCCESS'

export const MSG_TYPES = [
    MSG_TYPE_INIT,
    MSG_TYPE_INIT_REPLY,
    MSG_TYPE_RPC_CALL,
    MSG_TYPE_RPC_REPLY,
    MSG_TYPE_MESSAGE
];

